# Generated by Django 5.0.4 on 2024-04-26 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companies",
            name="application_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companies",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
